name: ci

on:
  push:
    branches:
      - box
    # paths:
    #   - '**.yml'
    #   - '**.json'
    #   - '**.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idf: ["v4.4.2"] 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"

        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

        - name: Install
          run: |
            sudo apt install -y git wget gperf cmake ninja-build ccache dfu-util

        - name: Build
          run: |
            git clone -b ${{ matrix.idf }} --recursive https://github.com/espressif/esp-idf.git
            cd esp-idf
            ./install.sh esp32s3
            . ./export.sh
            cd ..
            idf.py build
            idf.py uf2
            cd build
            esptool.py --chip esp32s3 merge_bin -o box-bridge-${{ matrix.idf }}.bin @flash_args
            mkdir output
            mv box-bridge-${{ matrix.idf }}.bin  output/
            mv uf2.bin  output/

        - name: Upload
          uses: actions/upload-artifact@v2
          with:
            name: box-bridge-${{ matrix.idf }}
            path: build/output
