name: ci

on:
  push:
    branches:
      - qitas
    # paths:
    #   - '**.yml'
    #   - '**.json'
    #   - '**.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - "esp32s2"
          - "esp32s3"
        idf: ["v4.4.2"] 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"

        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

        - name: Install
          if: matrix.os == 'ubuntu-latest'
          run: |
            sudo apt install -y git wget gperf cmake ninja-build ccache dfu-util

        - name: Build
          run: |
            git clone -b ${{ matrix.idf }} --recursive https://github.com/espressif/esp-idf.git
            cd esp-idf
            ./install.sh ${{ matrix.targets }}
            . ./export.sh
            cd ..
            idf.py set-target ${{ matrix.targets }}
            idf.py build
            idf.py uf2
            cd build
            esptool.py --chip ${{ matrix.targets }} merge_bin -o bridge-${{ matrix.targets }}-${{ matrix.esp-idf }}.bin @flash_args
            mkdir output
            mv bridge-${{ matrix.targets }}-${{ matrix.esp-idf }}.bin  output/
            mv uf2.bin  output/

        - name: Upload
          uses: actions/upload-artifact@v2
          with:
            name: ${{ matrix.targets }}-${{ matrix.examples }}-${{ matrix.esp-idf }}
            path: build/output
